# Generated by Django 5.1.1 on 2024-11-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Car", "0003_alter_car_date_finished"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="date_created",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="car",
            name="date_finished",
            field=models.DateField(),
        ),
    ]
