# Generated by Django 5.1.1 on 2024-11-17 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Car", "0004_alter_car_date_created_alter_car_date_finished"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="manufacturer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cars",
                to="Car.manufacturer",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="Car.car",
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Country"),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manufacturers",
                to="Car.country",
            ),
        ),
    ]
