# Generated by Django 5.1.1 on 2024-11-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Car", "0005_alter_car_manufacturer_alter_comment_car_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Manufacturer"
            ),
        ),
    ]
