# Generated by Django 5.1.1 on 2024-11-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Car", "0006_alter_country_name_alter_manufacturer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
    ]
